version: "2.2"

services:
 
  azure-sql-edge:
    image: mcr.microsoft.com/azure-sql-edge:${SQL_EDGE_VERSION}
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=${SQL_EDGE_SA_PASSWORD}
    ports:
      - ${SQL_EDGE_PORT}:1433
    networks:
      - uc-mvc-net
volumes:
  data01:
    driver: local
  kibanadata:
    driver: local

networks:
  uc-mvc-net:
    driver: bridge
